'use client';
import {useState,useEffect,useRef} from 'react';
import {Compass,Map,CalendarDays,Wallet,Plus,Sun,CloudSun,Route,Backpack,FileText,Users,Settings,Bell,ChevronDown,ArrowRight,Check as CheckIcon,WifiOff,Search,LayoutGrid,PanelLeft,MessageCircle,Sparkles,Send,Download,TriangleAlert,Loader2,ChevronRight} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Toaster} from '@/components/ui/sonner';
import {Skeleton} from '@/components/ui/skeleton';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {toast} from 'sonner';
import {Button,Notice,Input,Pick} from './ui';
import Wizard from './wizard';
import {TripContext,type View} from './context';
import {Explore,Comparison,MyTrips,Overview,Itinerary} from './core-views';
import {Budget,Expenses} from './budget-views';
import {Transport,Weather,MapExplorer} from './travel-views';
import {Checklist,Documents,Collaboration,Today,Profile} from './workspace-views';
import {type Trip,type TripInput,money,uid,inputSchema} from '@/lib/nusatrip/model';
import {demoTrips,generateTrip,totals,conflicts,previewDiff,displayCity,clock} from '@/lib/nusatrip/engine';
import {LocalTripRepository,STORAGE_KEY,validateTrips} from '@/lib/nusatrip/repository';
import {runAssistant} from '@/lib/nusatrip/providers';
import {getDestination} from '@/lib/nusatrip/catalog';
import {download,publicSnapshot} from '@/lib/nusatrip/exports';
import {z} from 'zod';
const nav:[View,string,typeof Compass][]=[['explore','Explore',Compass],['trips','Perjalananku',Map],['today','Today',Sun],['overview','Ringkasan trip',LayoutGrid],['itinerary','Itinerary',CalendarDays],['map','Peta perjalanan',Map],['budget','Budget planner',Wallet],['expenses','Pengeluaran',Wallet],['transport','Transport & stay',Route],['weather','Cuaca & Plan B',CloudSun],['checklist','Checklist & packing',Backpack],['documents','Catatan booking',FileText],['collaboration','Teman perjalanan',Users]];
const validViews=[...nav.map(x=>x[0]),'profile','compare','setup'];
export default function NusaTrip(){
 const [trips,setTrips]=useState<Trip[]>([]),[active,setActive]=useState(''),[view,setView]=useState<View>('explore'),[hydrated,setHydrated]=useState(false),[online,setOnline]=useState(true),[name,setName]=useState('Penjelajah'),[saveError,setSaveError]=useState(''),[compare,setCompare]=useState<string[]>([]),[wizardInitial,setWizardInitial]=useState<TripInput|undefined>(),[previous,setPrevious]=useState<Trip|null>(null),[pending,setPending]=useState<{trip:Trip;description:string}|null>(null),[assistant,setAssistant]=useState(false),[command,setCommand]=useState(''),[thinking,setThinking]=useState(false),[notifications,setNotifications]=useState(false),[savedAt,setSavedAt]=useState('');
 const repository=useRef<LocalTripRepository|null>(null),blocked=useRef(false),tripsRef=useRef(trips);tripsRef.current=trips;
 const trip=trips.find(t=>t.id===active)??trips[0];
 function snapshot(list:Trip[],id:string){const t=list.find(x=>x.id===id)??list[0];if(t)try{localStorage.setItem('nusatrip-offline',JSON.stringify({...publicSnapshot(t),budget:{total:totals(t).total,perPerson:totals(t).perPerson},checklist:t.checklist.map(c=>({name:c.name,done:c.done,quantity:c.quantity})),saved:t.updated}))}catch{}}
 function persist(list:Trip[]){if(blocked.current){setSaveError('Data berubah di tab lain atau data tersimpan bermasalah. Unduh cadangan lalu muat ulang sebelum menyimpan.');return false}try{repository.current?.save(list);setSaveError('');setSavedAt(new Date().toISOString());snapshot(list,active);return true}catch(e){setSaveError(e instanceof Error?e.message:'Gagal menyimpan.');return false}}
 useEffect(()=>{let list:Trip[]=[];try{repository.current=new LocalTripRepository(localStorage);list=repository.current.load()??demoTrips();if(!list.length)list=demoTrips();setTrips(list);const id=localStorage.getItem('nusatrip-active');setActive(list.some(t=>t.id===id)?id!:list[0].id);setName(localStorage.getItem('nusatrip-name')||'Penjelajah');repository.current.save(list);setSavedAt(new Date().toISOString());snapshot(list,id??list[0].id)}catch(e){blocked.current=true;list=demoTrips();setTrips(list);setActive(list[0].id);setSaveError(e instanceof Error?e.message:'Penyimpanan browser tidak tersedia.')}
 setOnline(navigator.onLine);setHydrated(true);const hash=()=>{const v=location.hash.slice(1);if(validViews.includes(v))setView(v as View)};hash();const on=()=>setOnline(true),off=()=>setOnline(false),storage=(e:StorageEvent)=>{if(e.key===STORAGE_KEY){blocked.current=true;setSaveError('Perjalanan diubah pada tab lain. Muat ulang sebelum melanjutkan agar perubahan tidak tertimpa.')}};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('hashchange',hash);window.addEventListener('storage',storage);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return ()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('hashchange',hash);window.removeEventListener('storage',storage)}},[]);
 function navigate(v:View){setView(v);window.location.hash=v;window.scrollTo({top:0,behavior:'instant'})}
 function openTrip(id:string,v:View='overview'){setActive(id);setPrevious(null);try{localStorage.setItem('nusatrip-active',id);snapshot(trips,id)}catch{}navigate(v)}
 function create(initial?:TripInput){setWizardInitial(initial);navigate('setup')}
 function commit(next:Trip,description:string){if(!online){toast.error('Sedang offline. Rencana dapat dibaca; perubahan menunggu koneksi.');return false}if(blocked.current){toast.error('Muat ulang untuk menyelesaikan konflik data di perangkat.');return false}try{inputSchema.parse(next.input);const failures=conflicts(next).filter(s=>!s.startsWith('Target budget'));if(failures.length){toast.error(failures[0]);return false}const updated={...next,updated:new Date().toISOString(),revisions:[...next.revisions,{id:uid(),at:new Date().toISOString(),description}].slice(-100)};const list=trips.map(t=>t.id===next.id?updated:t);validateTrips(list);setPrevious(trip);setTrips(list);const saved=persist(list);if(saved)toast.success(description);return true}catch(e){toast.error(e instanceof Error?e.message:'Data perjalanan tidak valid.');return false}}
 function propose(next:Trip,description:string){setPending({trip:next,description})}
 function onCreate(input:TripInput){if(!online||blocked.current)throw new Error('Koneksi atau penyimpanan belum siap. Muat ulang setelah masalah terselesaikan.');const next=generateTrip(input),failures=conflicts(next).filter(s=>!s.startsWith('Target budget'));if(failures.length)throw new Error(failures.join(' '));const list=[next,...trips];setTrips(list);persist(list);setActive(next.id);try{localStorage.setItem('nusatrip-active',next.id);snapshot(list,next.id)}catch{}setPrevious(null);navigate('itinerary');toast.success('Perjalananmu siap dijelajahi.')}
 function undo(){if(previous&&commit(previous,'Perubahan terakhir dibatalkan'))setPrevious(null)}
 function reset(){if(!online){toast.info('Reset tersedia saat online.');return}try{const list=demoTrips();blocked.current=false;repository.current?.save(list);setTrips(list);setActive(list[0].id);setPrevious(null);setSaveError('');localStorage.removeItem('nusatrip-draft');persist(list);navigate('explore');toast.success('Tiga trip contoh telah dipulihkan.')}catch{toast.error('Penyimpanan belum tersedia. Data tidak direset.')}}
 const actionRef=useRef({trip,navigate,propose});actionRef.current={trip,navigate,propose};
 useEffect(()=>{if(!hydrated)return;type Tool={name:string;description:string;title:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools:Tool[]=[{name:'read_active_trip_summary',title:'Baca ringkasan trip',description:'Baca itinerary dan budget tersanitasi; tidak mengembalikan dokumen atau booking pribadi.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){z.object({}).strict().parse(input);return publicSnapshot(actionRef.current.trip)}},{name:'stage_trip_adjustment',title:'Preview penyesuaian trip',description:'Tampilkan preview penyesuaian dari perintah. Tidak menerapkan perubahan; pengguna meninjau dampaknya.',inputSchema:{type:'object',properties:{command:{type:'string',minLength:1,maxLength:200}},required:['command'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const {command}=z.object({command:z.string().min(1).max(200)}).strict().parse(input);const next=await runAssistant(actionRef.current.trip,command);actionRef.current.propose(next,command);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:'preview',...previewDiff(actionRef.current.trip,next)}}}];for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}return ()=>life.abort()},[hydrated]);
 if(!hydrated||!trip)return <div className="app-loading"><div className="brand"><Compass/>NusaTrip</div><p>Menyiapkan perjalananmu…</p><Skeleton className="h-10 w-3/4"/><Skeleton className="h-64 w-full"/></div>;
 const ctx={trip,trips,view,online,name,navigate,openTrip,create,commit,propose,undo,canUndo:!!previous,compare,setCompare,saveError,retrySave:()=>persist(trips),reset,rename:(v:string)=>{if(!online){toast.info('Perubahan profil tersedia saat online.');return}setName(v);try{localStorage.setItem('nusatrip-name',v);toast.success('Nama disimpan')}catch{toast.error('Nama belum tersimpan di perangkat.')}},removeTrip:(id:string)=>{if(!online){toast.info('Sedang offline. Perjalanan hanya dapat dibaca.');return}if(trips.length===1){toast.info('Buat trip baru sebelum menghapus perjalanan terakhir.');return}const next=trips.filter(t=>t.id!==id);if(persist(next)){setTrips(next);if(id===active)openTrip(next[0].id,'trips');toast.success('Perjalanan dihapus')}}};
 const diff=pending?previewDiff(trip,pending.trip):null;const blocking=diff?.conflicts.filter(s=>!s.startsWith('Target budget'))??[];
 const views:Record<string,React.ReactNode>={explore:<Explore/>,compare:<Comparison/>,trips:<MyTrips/>,overview:<Overview/>,itinerary:<Itinerary/>,map:<MapExplorer/>,budget:<Budget/>,expenses:<Expenses/>,transport:<Transport/>,weather:<Weather/>,checklist:<Checklist/>,documents:<Documents/>,collaboration:<Collaboration/>,today:<Today/>,profile:<Profile/>,setup:<Wizard initial={wizardInitial} onCreate={onCreate} onClose={()=>navigate('explore')}/>};
 const due=trip.checklist.filter(x=>!x.done).sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,6);
 return <TripContext.Provider value={ctx}><SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><SidebarDismiss view={view} active={active}/><a href="#main-content" className="skip-link">Langsung ke konten</a><Sidebar className="app-sidebar"><SidebarHeader><button className="brand" onClick={()=>navigate('explore')}><span className="brand-icon"><Compass size={24}/></span>NusaTrip<span className="brand-dot">.</span></button><span className="brand-subtitle">CERITA BARU, DI NUSANTARA</span></SidebarHeader><SidebarContent><SidebarGroup><SidebarMenu>{nav.slice(0,3).map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>navigate(id)}><Icon size={19}/><span>{label}</span>{id==='trips'&&<span className="nav-count">{trips.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>WORKSPACE TRIP</SidebarGroupLabel><div className="sidebar-trip-select"><Pick label="Perjalanan aktif" value={trip.id} onChange={v=>openTrip(v)} options={trips.map(t=>({value:t.id,label:t.input.name}))}/></div><SidebarMenu>{nav.slice(3).map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>navigate(id)}><Icon size={18}/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><button className="assistant-sidebar" onClick={()=>setAssistant(true)}><Sparkles size={19}/><div><b>Teman merencanakan</b><span>Sesuaikan perjalananmu</span></div><ChevronRight size={15}/></button><button className={`profile-button ${view==='profile'?'active':''}`} onClick={()=>navigate('profile')}><span className="avatar">{name.charAt(0)}</span><div><b>{name}</b><small>Mode lokal</small></div><Settings size={17}/></button></SidebarFooter></Sidebar>
 <div className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>NusaTrip</span><ChevronRight size={13}/><b>{nav.find(n=>n[0]===view)?.[1]??(view==='setup'?'Perjalanan baru':view==='profile'?'Profil':'Perbandingan')}</b></div><div className="topbar-actions"><span className={`save-status ${!online?'offline':''}`}>{!online?<WifiOff size={14}/>:saveError?<TriangleAlert size={14}/>:<CheckIcon size={14}/>}<span>{!online?'Offline · baca saja':saveError?'Belum tersimpan':'Tersimpan di perangkat'}</span></span><button className="icon-button notification-button" aria-label="Pengingat persiapan" onClick={()=>setNotifications(true)}><Bell size={19}/>{due.length>0&&<span/>}</button><button className="avatar small" aria-label="Buka profil" onClick={()=>navigate('profile')}>{name.charAt(0)}</button></div></header><main id="main-content" className="workspace-content">{saveError&&<Notice tone="error">{saveError}<div className="button-row"><Button variant="outline" onClick={()=>download(JSON.stringify({version:1,trips},null,2),'nusatrip-cadangan-privat.json','application/json')}>Unduh cadangan privat</Button><Button variant="outline" onClick={()=>blocked.current?location.reload():persist(trips)}>{blocked.current?'Muat ulang':'Coba simpan lagi'}</Button></div></Notice>}{!online&&<Notice>Mode offline: rencana yang telah dibuka dapat dibaca. Terakhir disimpan {savedAt?new Date(savedAt).toLocaleString('id-ID'):'belum diketahui'}. Data mungkin kedaluwarsa; peta dan layanan eksternal memerlukan internet.</Notice>}<div key={`${trip.id}-${view}`}>{views[view]??<Explore/>}</div><footer className="workspace-footer"><span>Direncanakan dengan ruang untuk spontan.</span><button onClick={()=>navigate('profile')}>Tentang data & sumber<ArrowRight size={13}/></button></footer></main></div><nav className="mobile-bottom" aria-label="Navigasi utama">{[['explore','Explore',Compass],['trips','Trips',Map],['today','Today',Sun],['budget','Budget',Wallet],['profile','Profile',Users]].map(([id,label,I])=>{const Icon=I as typeof Compass;return <button key={id as string} className={view===id?'active':''} onClick={()=>navigate(id as View)}><Icon size={20}/><span>{label as string}</span></button>})}</nav><button className="assistant-fab" aria-label="Buka assistant perjalanan" onClick={()=>setAssistant(true)}><Sparkles size={21}/></button>
 <Dialog open={!!pending} onOpenChange={v=>!v&&setPending(null)}><DialogContent><DialogHeader><DialogTitle>{pending?.description}</DialogTitle><DialogDescription>Tinjau dampak perubahan pada perjalanan aktif sebelum menerapkan.</DialogDescription></DialogHeader>{diff&&<><div className="change-preview"><div><span>Perubahan biaya grup</span><b>{diff.cost>0?'+':diff.cost<0?'−':''}{money(Math.abs(diff.cost))}</b></div><div><span>Perubahan transfer</span><b>{diff.transfer>0?'+':''}{diff.transfer} menit</b></div><div><span>Aktivitas / jadwal berubah</span><b>{diff.changed}</b></div></div><p>Total baru <b>{money(totals(pending!.trip).total)}</b> · {money(totals(pending!.trip).perPerson)} / orang</p>{diff.conflicts.length>0&&<Notice tone={blocking.length?'error':'warning'}>{diff.conflicts.map((c,j)=><p key={j}>{c}</p>)}</Notice>}{blocking.length>0&&<p className="small-copy">Perubahan belum bisa diterapkan. Kurangi aktivitas, sesuaikan durasi atau budget, atau buka kunci item yang konflik.</p>}</>}<DialogFooter><Button variant="outline" onClick={()=>setPending(null)}>Batal</Button><Button disabled={blocking.length>0||!online} onClick={()=>{if(pending&&commit(pending.trip,pending.description))setPending(null)}}>Terapkan perubahan</Button></DialogFooter></DialogContent></Dialog>
 <Sheet open={assistant} onOpenChange={setAssistant}><SheetContent className="assistant-sheet"><SheetHeader><div className="assistant-symbol"><Sparkles size={25}/></div><SheetTitle>Teman merencanakan</SheetTitle><SheetDescription>{trip.input.name} · memakai data trip aktif</SheetDescription></SheetHeader><div className="sheet-body"><h2>Butuh sedikit penyesuaian?</h2><p>Pilih ide atau tulis perintah singkat. Setiap perubahan bisa kamu tinjau dulu.</p><div className="assistant-suggestions">{['Hari 3 lebih santai','Hemat budget perjalanan','Ganti pantai dengan indoor','Jangan pakai kapal','Tambahkan kuliner lokal'].map(s=><button key={s} onClick={()=>setCommand(s)}>{s}<ArrowRight size={15}/></button>)}</div><Input label="Apa yang ingin kamu ubah?" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')document.getElementById('assistant-submit')?.click()}} placeholder="Mis. hari 2 lebih santai"/><Button id="assistant-submit" disabled={!command.trim()||thinking} onClick={async()=>{setThinking(true);try{const next=await runAssistant(trip,command);setAssistant(false);propose(next,command)}catch(e){toast.error(e instanceof Error?e.message:'Perintah belum dapat diproses.')}finally{setThinking(false)}}}>{thinking?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>}Preview penyesuaian</Button><Notice>Penyesuaian menggunakan aturan. Percakapan AI bebas belum terhubung. Nilai penghematan mengikuti alternatif yang tersedia; aktivitas terkunci dipertahankan.</Notice></div></SheetContent></Sheet>
 <Dialog open={notifications} onOpenChange={setNotifications}><DialogContent><DialogHeader><DialogTitle>Pengingat persiapan</DialogTitle><DialogDescription>Pengingat dalam aplikasi untuk trip aktif. Tidak ada push atau email otomatis.</DialogDescription></DialogHeader>{due.map(t=><button className="reminder" key={t.id} onClick={()=>{setNotifications(false);navigate('checklist')}}><CalendarDays size={18}/><div><b>{t.name}</b><small>{t.deadline}</small></div><ArrowRight size={16}/></button>)}{!due.length&&<p>Semua persiapan sudah selesai.</p>}</DialogContent></Dialog><PrintTrip trip={trip}/><Toaster position="bottom-right" richColors/></SidebarProvider></TripContext.Provider>
}
function PrintTrip({trip}:{trip:Trip}){const s=totals(trip);return <div className="print-trip"><h1>NusaTrip · {trip.input.name}</h1><p>{trip.input.origin} → {trip.input.cities.map(displayCity).join(' → ')} · {trip.input.days} hari {trip.input.days-1} malam</p><p>Total simulasi grup {money(s.total)} · per orang {money(s.perPerson)} · cadangan {money(s.reserve)}</p><p>Harga dan jadwal contoh; jam operasional dan koordinat belum diverifikasi. Dicetak dari rencana terbaru.</p>{trip.days.map((d,j)=><section key={d.id}><h2>Hari {j+1} · {d.date} · {displayCity(d.city)}</h2><p>Zona waktu {getDestination(d.city).timezone}</p><table><thead><tr><th>Waktu</th><th>Aktivitas</th><th>Area</th><th>Transfer</th><th>Biaya satuan</th></tr></thead><tbody>{d.items.filter(x=>x.status!=='skipped').map(x=><tr key={x.id}><td>{clock(x.start)}–{clock(x.end)}</td><td>{x.title}</td><td>{x.area}</td><td>{x.transfer} menit</td><td>{money(x.cost)}{x.basis==='person'?' / orang':' / grup'}</td></tr>)}</tbody></table></section>)}</div>}

function SidebarDismiss({view,active}:{view:View;active:string}){const {setOpenMobile}=useSidebar();useEffect(()=>{setOpenMobile(false)},[view,active,setOpenMobile]);return null}
