'use client';
import {useState,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Check as CheckIcon,Sparkles,Plane,Wallet,Heart,Route} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {type TripInput,vibes,modes,defaultInput,inputSchema,money} from '@/lib/nusatrip/model';
import {destinations} from '@/lib/nusatrip/catalog';
import {people,cap,nightsFor} from '@/lib/nusatrip/engine';
import {Button,Input,Pick,Check,Notice} from './ui';
export default function Wizard({initial,onCreate,onClose}:{initial?:TripInput;onCreate:(input:TripInput)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState<TripInput>(initial??{...defaultInput,name:'Perjalanan baruku'}),[step,setStep]=useState(0),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{if(!initial)try{const saved=localStorage.getItem('nusatrip-draft');if(saved){const d=inputSchema.safeParse(JSON.parse(saved));if(d.success)setDraft(d.data)}}catch{}setLoaded(true)},[initial]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('nusatrip-draft',JSON.stringify(draft))}catch{setError('Draft belum tersimpan di perangkat. Tetap di halaman ini sampai trip dibuat.')}},[draft,loaded]);
 function update<K extends keyof TripInput>(key:K,value:TripInput[K]){setDraft(d=>({...d,[key]:value,...(key==='cities'||key==='days'?{nights:undefined}:{}),...(key==='adults'||key==='children'?{rooms:Math.max(d.rooms,Math.ceil(((key==='adults'?value as number:d.adults)+(key==='children'?value as number:d.children))/2))}:{})}));setError('')}
 const listToggle=(key:'cities'|'vibes'|'modes'|'avoid',value:string)=>update(key,draft[key].includes(value)?draft[key].filter(x=>x!==value):[...draft[key],value]);
 const numbers=(key:keyof TripInput,label:string,min:number,max:number)=> <Input label={label} type="number" min={min} max={max} value={String(draft[key]??'')} onChange={e=>update(key,Number(e.target.value) as never)}/>;
 function next(){const r=inputSchema.safeParse(draft);if(!r.success){setError(r.error.issues.map(x=>x.message).join(' '));return}if(step<3)setStep(step+1);else try{onCreate(draft)}catch(e){setError(e instanceof Error?e.message:'Rencana belum dapat dibuat. Periksa input.') }}
 const steps=[{name:'Rencana dasar',icon:Plane},{name:'Budget',icon:Wallet},{name:'Gaya liburan',icon:Heart},{name:'Perjalanan',icon:Route}];
 return <div className="wizard"><div className="eyebrow">PERJALANAN VERSIMU</div><div className="page-heading"><div><h1>Mau ke mana kali ini?</h1><p>Mulai dari yang penting. Rencana bisa kamu ubah nanti.</p></div><Button variant="outline" onClick={onClose}>Tutup</Button></div><div className="wizard-layout"><section className="surface wizard-main"><div className="wizard-steps">{steps.map((s,j)=><button key={s.name} disabled={j>step} onClick={()=>setStep(j)} className={step===j?'active':step>j?'complete':''}><span>{step>j?<CheckIcon size={16}/>:j+1}</span>{s.name}</button>)}</div><Progress value={(step+1)*25} className="wizard-progress"/>
 {step===0&&<div className="form-section"><h2>Kenali rencana besarnya</h2><div className="form-grid"><Input label="Nama perjalanan" value={draft.name} onChange={e=>update('name',e.target.value)}/><Pick label="Kota asal" value={draft.origin} onChange={v=>update('origin',v)} options={['Bali','Jakarta','Semarang','Surabaya','Yogyakarta','Makassar','Lombok','Jayapura']}/><Input label={draft.flexible?'Tanggal patokan (boleh berubah)':'Tanggal berangkat'} type="date" value={draft.date} onChange={e=>update('date',e.target.value)}/>{numbers('days','Durasi (hari)',2,21)}{numbers('adults','Dewasa',1,12)}{numbers('children','Anak',0,8)}<Pick label="Pergi bersama" value={draft.group} onChange={v=>update('group',v)} options={['Solo','Pasangan','Keluarga','Teman']}/><Pick label="Tujuan" value={draft.cities.length>1?'multi':'single'} onChange={v=>update('cities',v==='single'?[draft.cities[0]??'lombok']:['semarang','surabaya'])} options={[{value:'single',label:'Satu destinasi'},{value:'multi',label:'Beberapa kota'}]}/></div><Check label="Tanggal saya fleksibel" checked={draft.flexible} onChange={v=>update('flexible',v)}/><div><label className="field-label">Pilih destinasi · maksimal 3, sesuai urutan kunjungan</label><div className="chips">{destinations.map(d=><button key={d.id} className={draft.cities.includes(d.id)?'chip selected':'chip'} aria-pressed={draft.cities.includes(d.id)} onClick={()=>listToggle('cities',d.id)}>{draft.cities.includes(d.id)&&`${draft.cities.indexOf(d.id)+1}. `}{d.name}</button>)}</div></div><Notice>{draft.days} hari berarti {draft.days} tanggal perjalanan dan {Math.max(0,draft.days-1)} malam menginap. Tarif anak dalam simulasi disamakan dengan dewasa; konfirmasi harga sebenarnya.</Notice></div>}
 {step===1&&<div className="form-section"><h2>Budget yang terasa pas</h2><div className="form-grid">{numbers('budget','Budget (Rp)',100000,500000000)}<Pick label="Basis budget" value={draft.budgetBasis} onChange={v=>update('budgetBasis',v as 'group'|'person')} options={[{value:'group',label:'Total seluruh peserta'},{value:'person',label:'Per orang'}]}/>{numbers('reserve','Dana cadangan (%)',0,30)}<Pick label="Prioritas pengeluaran" value={draft.priority} onChange={v=>update('priority',v)} options={['Hotel','Kuliner','Aktivitas','Transportasi']}/>{numbers('rooms','Jumlah kamar · kapasitas 2 orang',1,10)}{numbers('roomRate','Asumsi harga kamar / malam (Rp)',50000,10000000)}{numbers('localRate','Kendaraan lokal / hari (Rp)',0,5000000)}{numbers('foodRate','Makan / orang / hari (Rp)',10000,2000000)}</div><Check label="Budget termasuk transport pergi dan pulang" checked={draft.includeTransport} onChange={v=>update('includeTransport',v)}/><Check label="Gunakan batas budget wajib (hard cap)" checked={draft.hardCap} onChange={v=>update('hardCap',v)}/><Notice>Harga di sini adalah asumsi yang bisa diedit. Rencana dengan batas budget wajib tidak dapat disimpan jika totalnya melampaui batas.</Notice></div>}
 {step===2&&<div className="form-section"><h2>Liburan seperti apa yang kamu bayangkan?</h2><div className="chips vibes">{vibes.map(v=><button key={v} aria-pressed={draft.vibes.includes(v)} onClick={()=>listToggle('vibes',v)} className={draft.vibes.includes(v)?'chip selected':'chip'}>{v}</button>)}</div><div className="form-grid"><Pick label="Ritme perjalanan" value={draft.pace} onChange={v=>update('pace',v as TripInput['pace'])} options={['Santai','Seimbang','Padat']}/><Pick label="Toleransi jalan kaki" value={draft.walking} onChange={v=>update('walking',v as TripInput['walking'])} options={['Rendah','Sedang','Tinggi']}/><Input label="Mulai aktivitas" type="time" value={draft.start} onChange={e=>update('start',e.target.value)}/><Input label="Selesai aktivitas" type="time" value={draft.end} onChange={e=>update('end',e.target.value)}/><Input label="Makanan & pantangan" placeholder="Mis. halal, vegetarian, alergi kacang" value={draft.diet} onChange={e=>update('diet',e.target.value)}/></div><Check label="Saya memerlukan aksesibilitas tambahan" checked={draft.accessibility} onChange={v=>update('accessibility',v)}/>{draft.accessibility&&<Notice>Rencana akan menghindari aktivitas fisik tinggi. Akses kursi roda dan fasilitas setiap tempat masih perlu dikonfirmasi langsung.</Notice>}<div><label className="field-label">Destinasi yang ingin dihindari</label><div className="chips">{destinations.map(d=><button key={d.id} aria-pressed={draft.avoid.includes(d.id)} className={draft.avoid.includes(d.id)?'chip selected':'chip'} onClick={()=>listToggle('avoid',d.id)}>{d.name}</button>)}</div></div></div>}
 {step===3&&<div className="form-section"><h2>Atur perjalanan, sisakan ruang untuk jeda</h2><label className="field-label">Moda yang bersedia kamu gunakan</label><div className="chips">{modes.map(m=><button key={m} aria-pressed={draft.modes.includes(m)} className={draft.modes.includes(m)?'chip selected':'chip'} onClick={()=>listToggle('modes',m)}>{m}</button>)}</div><div className="form-grid"><Input label="Asumsi tiba di destinasi · waktu lokal" type="time" value={draft.arrival} onChange={e=>update('arrival',e.target.value)}/><Input label="Asumsi berangkat pulang · waktu lokal" type="time" value={draft.departure} onChange={e=>update('departure',e.target.value)}/>{numbers('maxHotels','Maksimum perpindahan hotel',0,5)}{numbers('maxTransfer','Maksimum transfer / hari (menit)',30,900)}{numbers('buffer','Buffer keberangkatan (menit)',60,240)}<Pick label="Toleransi hujan" value={draft.rain} onChange={v=>update('rain',v as TripInput['rain'])} options={['Rendah','Sedang','Tinggi']}/><Pick label="Aktivitas pilihan" value={draft.outdoor} onChange={v=>update('outdoor',v as TripInput['outdoor'])} options={['Campuran','Indoor','Outdoor']}/></div><Check label="Bersedia menyeberang atau beraktivitas laut" checked={draft.sea} onChange={v=>update('sea',v)}/><Check label="Berencana menggunakan laundry" checked={draft.laundry} onChange={v=>update('laundry',v)}/><Notice>Jam transport adalah asumsi perencanaan. Cocokkan dengan tiket sebelum melakukan perjalanan.</Notice></div>}
 {error&&<Notice tone="error">{error}</Notice>}<div className="wizard-footer"><Button variant="ghost" onClick={()=>step?setStep(step-1):onClose()}><ArrowLeft size={16}/>{step?'Kembali':'Batal'}</Button><Button onClick={next}>{step===3?<><Sparkles size={16}/>Buat itinerary</>:<>Lanjutkan<ArrowRight size={16}/></>}</Button></div></section><aside className="wizard-summary surface"><div className="eyebrow">RENCANA SEMENTARA</div><h3>{draft.name||'Perjalanan barumu'}</h3><p>{draft.origin} → {draft.cities.map(id=>destinations.find(d=>d.id===id)?.name).join(' → ')}</p><dl><div><dt>Durasi</dt><dd>{draft.days} hari, {draft.days-1} malam</dd></div><div><dt>Peserta</dt><dd>{people(draft)} orang</dd></div><div><dt>Budget grup</dt><dd>{money(cap(draft))}</dd></div><div><dt>Ritme</dt><dd>{draft.pace}</dd></div></dl>{draft.cities.map((c,j)=><p key={c} className="night-allocation">{destinations.find(d=>d.id===c)?.name}<b>{nightsFor(draft)[j]} malam</b></p>)}<span className="data-badge">Simulasi · bisa kamu sesuaikan</span></aside></div></div>
}
