import images from './images.json';
import type { Destination, Place } from './model';
const stamp='2026-09-10';
type Seed=[string,string,boolean,number,number,number?,boolean?];
const sources={bali:'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara.html',lombok:'https://www.indonesia.travel/gb/en/destinations/bali-nusa-tenggara/lombok.html',java:'https://www.indonesia.travel/gb/en/destinations/java.html',sulawesi:'https://www.indonesia.travel/gb/en/destinations/sulawesi.html'};
function make(id:string,name:string,region:string,subtitle:string,area:string,lat:number,lng:number,timezone:string,tags:string[],outdoor:number,costFactor:number,seeds:Seed[],source:string):Destination{
 const places:Place[]=seeds.map(([title,zone,indoor,duration,cost,walking=1,sea=false],i)=>({id:`${id}-${i}`,city:id,name:title,area:zone,category:/kuliner|kopi|masak|jajan/i.test(title)?'Kuliner':indoor?'Budaya':/pantai|bukit|taman|teluk/i.test(title)?'Alam':'Relaksasi',indoor,duration,cost,lat:lat+(i%4-1.5)*.009,lng:lng+(Math.floor(i/4)-.5)*.012,walking,sea,reservation:/kelas|workshop|snorkeling/i.test(title),provenance:{status:'Contoh',source:'Katalog editorial NusaTrip',url:source,updated:stamp,verified:false,assumptions:'Nama kegiatan adalah ide perencanaan. Harga, durasi, koordinat area dan ketersediaan adalah contoh; tempat, jam buka dan akses perlu dikonfirmasi.'}}));
 return {id,name,region,subtitle,description:subtitle+'. Pilih area menginap dekat aktivitas agar lebih banyak waktu untuk menikmati perjalanan.',vibes:tags,image:images[id as keyof typeof images],area,lat,lng,timezone,outdoor,guideDays:'4–6 hari · panduan editorial',transferNote:outdoor>65?'Aktivitas tersebar; sisihkan waktu untuk kendaraan lokal.':'Aktivitas kota lebih mudah diganti ketika hujan.',costFactor,source,places};
}
export const destinations:Destination[]=[
 make('lombok','Lombok','NUSA TENGGARA BARAT','Pantai tenang, hari-hari yang lebih pelan','Senggigi',-8.498,116.048,'Asia/Makassar',['Pantai & snorkeling','Slow travel','Alam & petualangan','Romantis','Photography'],75,1,[['Jalan santai di pesisir Senggigi','Senggigi',false,90,20000],['Santai di pantai','Senggigi',false,120,25000],['Kelas masak Sasak','Senggigi',true,120,175000],['Kopi dan jurnal perjalanan','Senggigi',true,60,45000],['Jelajah kerajinan lokal','Mataram',true,90,40000],['Kuliner khas Lombok','Mataram',true,90,70000],['Workshop tenun','Mataram',true,120,120000],['Photography pesisir','Senggigi',false,90,10000],['Snorkeling dengan operator lokal','Senggigi',false,180,300000,2,true],['Membaca di kafe','Mataram',true,75,40000]],sources.lombok),
 make('semarang','Semarang','JAWA TENGAH','Cerita kota lama dan rasa yang selalu dicari','Kota Lama',-6.969,110.426,'Asia/Jakarta',['Kuliner','Budaya & sejarah','City exploration','Photography','Budget trip'],35,.85,[['Jelajah Kota Lama','Kota Lama',false,120,10000],['Galeri seni dan kerajinan','Kota Lama',true,90,35000],['Kopi di bangunan heritage','Kota Lama',true,75,45000],['Photography arsitektur','Kota Lama',false,90,10000],['Jelajah kawasan Tugu Muda','Pusat kota',false,90,20000],['Kelas masak lumpia','Pusat kota',true,120,150000],['Jajan khas Semarang','Pusat kota',true,90,65000],['Workshop batik','Pusat kota',true,120,100000],['Toko buku dan waktu santai','Kota Lama',true,75,35000]],sources.java),
 make('surabaya','Surabaya','JAWA TIMUR','Kota penuh cerita, kuliner penuh karakter','Pusat Surabaya',-7.259,112.746,'Asia/Jakarta',['Kuliner','City exploration','Budaya & sejarah','Budget trip'],35,.9,[['Jelajah kawasan Tunjungan','Pusat Surabaya',false,90,10000],['Kopi di pusat kota','Pusat Surabaya',true,75,45000],['Galeri seni lokal','Pusat Surabaya',true,90,35000],['Kuliner khas Surabaya','Pusat Surabaya',true,90,65000],['Jalan santai kota lama','Kota Lama',false,90,10000],['Workshop kriya','Kota Lama',true,120,100000],['Photography heritage','Kota Lama',false,90,15000],['Kelas masak Jawa Timur','Pusat Surabaya',true,120,150000],['Toko buku dan sore santai','Pusat Surabaya',true,60,30000]],sources.java),
 make('makassar','Makassar','SULAWESI SELATAN','Senja di pesisir, budaya dan meja penuh rasa','Ujung Pandang',-5.138,119.407,'Asia/Makassar',['Kuliner','Budaya & sejarah','City exploration','Hidden gems'],50,.95,[['Jelajah kawasan Losari','Ujung Pandang',false,90,10000],['Jelajah kawasan Fort Rotterdam','Ujung Pandang',false,90,20000],['Kopi dan kudapan Makassar','Ujung Pandang',true,75,45000],['Kelas masak Sulawesi','Ujung Pandang',true,120,150000],['Workshop kerajinan lokal','Pusat Makassar',true,120,100000],['Kuliner khas Makassar','Pusat Makassar',true,90,70000],['Galeri budaya lokal','Pusat Makassar',true,90,30000],['Photography pesisir','Ujung Pandang',false,90,10000],['Waktu santai di kafe','Ujung Pandang',true,90,35000]],sources.sulawesi),
 make('bali','Bali','BALI','Budaya, sudut hijau, dan ruang untuk jeda','Ubud',-8.507,115.263,'Asia/Makassar',['Budaya & sejarah','Alam & petualangan','Premium comfort','Romantis','Keluarga'],65,1.1,[['Jalan santai kawasan Ubud','Ubud',false,90,20000],['Galeri seni Bali','Ubud',true,90,80000],['Kelas masak Bali','Ubud',true,120,200000],['Workshop kerajinan','Ubud',true,120,125000],['Jelajah taman dan kebun','Ubud',false,90,50000],['Kopi dan kuliner lokal','Ubud',true,90,70000],['Photography lanskap','Ubud',false,90,30000],['Yoga pemula di studio','Ubud',true,75,120000],['Waktu santai di kafe','Ubud',true,75,45000]],sources.bali),
 make('sumba','Sumba','NUSA TENGGARA TIMUR','Lanskap terbuka dan kisah yang hidup','Tambolaka',-9.429,119.245,'Asia/Makassar',['Alam & petualangan','Budaya & sejarah','Photography','Hidden gems'],80,1.3,[['Jelajah lanskap sekitar Tambolaka','Tambolaka',false,120,50000,2],['Photography pesisir','Tambolaka',false,120,30000],['Workshop tenun Sumba','Tambolaka',true,120,150000],['Kuliner lokal Sumba','Tambolaka',true,90,75000],['Kisah budaya bersama pemandu','Tambolaka',true,90,125000],['Jalan santai pesisir','Tambolaka',false,90,25000],['Kopi dan jurnal perjalanan','Tambolaka',true,75,50000],['Kerajinan dan oleh-oleh lokal','Tambolaka',true,90,40000],['Kelas masak lokal','Tambolaka',true,120,175000]],sources.bali),
 make('banyuwangi','Banyuwangi','JAWA TIMUR','Budaya Osing dan alam di ujung Jawa','Pusat Banyuwangi',-8.218,114.368,'Asia/Jakarta',['Alam & petualangan','Budaya & sejarah','Hidden gems','Budget trip'],70,.85,[['Jalan santai kota Banyuwangi','Pusat Banyuwangi',false,90,10000],['Workshop batik lokal','Pusat Banyuwangi',true,120,100000],['Kuliner Osing','Pusat Banyuwangi',true,90,65000],['Galeri budaya lokal','Pusat Banyuwangi',true,90,30000],['Photography pesisir','Pesisir kota',false,90,20000],['Jeda di tepi pantai','Pesisir kota',false,120,25000],['Kopi dan cerita lokal','Pusat Banyuwangi',true,75,35000],['Kelas masak Osing','Pusat Banyuwangi',true,120,125000],['Kerajinan khas Banyuwangi','Pusat Banyuwangi',true,90,45000]],sources.java)
];
export const getDestination=(id:string)=>{const d=destinations.find(d=>d.id===id);if(!d)throw new Error('Destinasi tidak dikenal. Pilih dari katalog.');return d};
export const getPlace=(id?:string)=>destinations.flatMap(d=>d.places).find(p=>p.id===id);
export const catalogOptions=[...destinations.map(d=>({id:d.id,name:d.name,cities:[d.id]})),{id:'semarang-surabaya',name:'Semarang–Surabaya',cities:['semarang','surabaya']}];
