import {z} from 'zod';
import type {Trip,Expense} from './model';
export const expenseSchema=z.object({id:z.string(),name:z.string().min(1,'Isi nama transaksi.').max(100),amount:z.number().int().positive('Nominal harus lebih dari nol.').max(500000000),category:z.string(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),payer:z.string(),shares:z.record(z.number().int().nonnegative()),kind:z.enum(['expense','refund']),splitMode:z.enum(['equal','percent','custom']),plannedId:z.string().optional()}).refine(x=>Object.values(x.shares).reduce((a,b)=>a+b,0)===x.amount,'Jumlah pembagian harus sama dengan nominal transaksi.');
export function allocate(amount:number,ids:string[],mode:'equal'|'percent'|'custom',values:Record<string,number>={}):Record<string,number>{
 if(!Number.isSafeInteger(amount)||amount<=0)throw new Error('Nominal harus berupa rupiah bulat positif.');
 const sorted=[...new Set(ids)].sort();if(!sorted.length)throw new Error('Pilih minimal satu penanggung biaya.');
 if(mode==='custom'){if(sorted.some(id=>!Number.isSafeInteger(values[id])||values[id]<0)||sorted.reduce((s,id)=>s+values[id],0)!==amount)throw new Error('Total nominal pembagian harus sama dengan transaksi.');return Object.fromEntries(sorted.map(id=>[id,values[id]]));}
 const weights=sorted.map(id=>mode==='equal'?1:values[id]);if(weights.some(v=>!Number.isFinite(v)||v<0)||mode==='percent'&&Math.abs(weights.reduce((a,b)=>a+b,0)-100)>.000001)throw new Error('Persentase harus tepat 100%.');
 const total=weights.reduce((a,b)=>a+b,0),raw=sorted.map((id,i)=>({id,value:amount*weights[i]/total})),result:Record<string,number>=Object.fromEntries(raw.map(x=>[x.id,Math.floor(x.value)]));let remainder=amount-Object.values(result).reduce((a,b)=>a+b,0);
 raw.sort((a,b)=>(b.value%1)-(a.value%1)||a.id.localeCompare(b.id));for(const r of raw){if(remainder--<=0)break;result[r.id]++}return result;
}
export function validateExpense(e:Expense,t:Trip){expenseSchema.parse(e);const ids=t.participants.map(p=>p.id);if(!ids.includes(e.payer)||Object.keys(e.shares).some(id=>!ids.includes(id)))throw new Error('Pembayar dan penanggung harus peserta perjalanan.');}
export function balances(t:Trip){const b:Record<string,number>=Object.fromEntries(t.participants.map(p=>[p.id,0]));for(const e of t.expenses){const sign=e.kind==='refund'?-1:1;b[e.payer]+=e.amount*sign;for(const [id,share] of Object.entries(e.shares))b[id]-=share*sign;}for(const s of t.settlements){b[s.from]+=s.amount;b[s.to]-=s.amount}return b;}
export function settlements(t:Trip){const b=balances(t),debt=Object.entries(b).filter(([,v])=>v<0).map(([id,v])=>({id,amount:-v})),credit=Object.entries(b).filter(([,v])=>v>0).map(([id,v])=>({id,amount:v})),out:{from:string;to:string;amount:number}[]=[];let a=0,c=0;while(a<debt.length&&c<credit.length){const amount=Math.min(debt[a].amount,credit[c].amount);out.push({from:debt[a].id,to:credit[c].id,amount});debt[a].amount-=amount;credit[c].amount-=amount;if(!debt[a].amount)a++;if(!credit[c].amount)c++;}return out;}
