import { z } from 'zod';
export const vibes = ['Pantai & snorkeling','Alam & petualangan','Kuliner','Budaya & sejarah','City exploration','Slow travel','Romantis','Keluarga','Budget trip','Premium comfort','Photography','Hidden gems'];
export const modes = ['Pesawat','Kereta','Mobil','Motor','Kapal'];
export const money = (n:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
export const uid = () => globalThis.crypto?.randomUUID?.() ?? `id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export const inputSchema = z.object({
  name:z.string().min(2).max(100),origin:z.string().min(2),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v,'Tanggal tidak valid'),flexible:z.boolean(),days:z.number().int().min(2).max(21),adults:z.number().int().min(1).max(12),children:z.number().int().min(0).max(8),group:z.string(),cities:z.array(z.string()).min(1).max(3),budget:z.number().int().min(100000).max(500000000),budgetBasis:z.enum(['group','person']),includeTransport:z.boolean(),reserve:z.number().int().min(0).max(30),hardCap:z.boolean(),priority:z.string(),vibes:z.array(z.string()).min(1),pace:z.enum(['Santai','Seimbang','Padat']),start:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/),end:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/),arrival:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/),departure:z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/),walking:z.enum(['Rendah','Sedang','Tinggi']),accessibility:z.boolean(),diet:z.string().max(300),avoid:z.array(z.string()),modes:z.array(z.string()).min(1),sea:z.boolean(),maxHotels:z.number().int().min(0).max(5),maxTransfer:z.number().int().min(30).max(900),rain:z.enum(['Rendah','Sedang','Tinggi']),outdoor:z.enum(['Campuran','Indoor','Outdoor']),rooms:z.number().int().min(1).max(10),roomRate:z.number().int().min(50000).max(10000000),localRate:z.number().int().min(0).max(5000000),foodRate:z.number().int().min(10000).max(2000000),buffer:z.number().int().min(60).max(240),laundry:z.boolean(),nights:z.array(z.number().int().min(1)).optional()
}).superRefine((v,c)=>{
 if(v.end<=v.start)c.addIssue({code:'custom',path:['end'],message:'Jam selesai harus setelah jam mulai.'});
 if(v.rooms*2<v.adults+v.children)c.addIssue({code:'custom',path:['rooms'],message:'Satu kamar contoh berkapasitas dua orang. Tambahkan kamar.'});
 if(new Set(v.cities).size!==v.cities.length)c.addIssue({code:'custom',path:['cities'],message:'Kota tidak boleh berulang.'});
 if(v.cities.length>v.days-1)c.addIssue({code:'custom',path:['cities'],message:'Sediakan minimal satu malam per kota.'});
 if(v.nights&&(v.nights.length!==v.cities.length||v.nights.reduce((a,b)=>a+b,0)!==v.days-1))c.addIssue({code:'custom',path:['nights'],message:'Pembagian malam harus sama dengan durasi dikurangi satu.'});
});
export type TripInput=z.infer<typeof inputSchema>;
export type DataStatus='Live'|'Estimasi'|'Contoh'|'Input pengguna';
export interface Provenance{status:DataStatus;source:string;url?:string;updated:string;verified:boolean;assumptions:string}
export interface Destination{id:string;name:string;region:string;subtitle:string;description:string;vibes:string[];image:string;area:string;timezone:string;lat:number;lng:number;outdoor:number;guideDays:string;transferNote:string;costFactor:number;source:string;places:Place[]}
export interface Place{id:string;city:string;name:string;area:string;category:'Alam'|'Budaya'|'Kuliner'|'Relaksasi';indoor:boolean;duration:number;cost:number;lat:number;lng:number;walking:number;sea:boolean;reservation:boolean;opening?:[number,number];provenance:Provenance}
export interface ItineraryItem{id:string;placeId?:string;title:string;city:string;area:string;kind:'activity'|'meal'|'rest'|'transfer'|'hotel';duration:number;start:number;end:number;transfer:number;cost:number;basis:'person'|'group';indoor:boolean;lat?:number;lng?:number;locked:boolean;fixed:boolean;status:'planned'|'done'|'skipped';note:string;reservation:boolean;opening?:[number,number];source:DataStatus;comments:{id:string;text:string;author:string}[]}
export interface TripDay{id:string;date:string;city:string;theme:string;locked:boolean;items:ItineraryItem[]}
export interface TransportLeg{id:string;from:string;to:string;mode:string;date:string;departure:string;arrival:string;fromTimezone:string;toTimezone:string;duration:number;cost:number;reference:string;confirmed:boolean}
export interface Accommodation{id:string;city:string;area:string;name:string;rooms:number;capacity:number;nights:number;rate:number;checkin:string;checkout:string;reference:string;confirmed:boolean}
export interface BudgetItem{id:string;name:string;category:string;unit:number;quantity:number;basis:string;total:number;status:DataStatus;source:string;city?:string}
export interface Expense{id:string;name:string;amount:number;category:string;date:string;payer:string;shares:Record<string,number>;kind:'expense'|'refund';splitMode:'equal'|'percent'|'custom';plannedId?:string}
export interface ChecklistItem{id:string;name:string;group:string;done:boolean;quantity:number;deadline:string;assignee:string}
export interface TripParticipant{id:string;name:string;role:'Owner'|'Editor'|'Viewer'}
export interface DocumentReference{id:string;title:string;reference:string;note:string}
export interface TripRevision{id:string;at:string;description:string}
export interface Trip{id:string;input:TripInput;days:TripDay[];legs:TransportLeg[];stays:Accommodation[];expenses:Expense[];extraBudget?:{id:string;name:string;category:string;unit:number;quantity:number;basis:'person'|'group'}[];participants:TripParticipant[];checklist:ChecklistItem[];documents:DocumentReference[];votes:Record<string,string[]>;settlements:{id:string;from:string;to:string;amount:number}[];revisions:TripRevision[];created:string;updated:string;generation:number}
export const defaultInput:TripInput={name:'Lombok, pelan-pelan',origin:'Bali',date:'2026-12-21',flexible:false,days:6,adults:2,children:0,group:'Teman',cities:['lombok'],budget:12000000,budgetBasis:'group',includeTransport:true,reserve:10,hardCap:false,priority:'Aktivitas',vibes:['Pantai & snorkeling','Slow travel'],pace:'Santai',start:'09:00',end:'20:00',arrival:'11:00',departure:'18:00',walking:'Sedang',accessibility:false,diet:'',avoid:[],modes:['Pesawat','Mobil'],sea:false,maxHotels:1,maxTransfer:360,rain:'Sedang',outdoor:'Campuran',rooms:1,roomRate:450000,localRate:300000,foodRate:125000,buffer:120,laundry:false};
