import {z} from 'zod';
import type {Place,Trip,TripInput,Provenance} from './model';
import {getDestination} from './catalog';
import {generateTrip,adjustTrip,type Adjustment} from './engine';
export interface WeatherSnapshot{kind:'forecast'|'climatology'|'demo'|'unavailable';city:string;days:{date:string;rain:number|null;min:number|null;max:number|null}[];provenance:Provenance;message:string}
export interface WeatherProvider{get(city:string,date:string,days:number):Promise<WeatherSnapshot>}
export interface PlacesProvider{search(city:string,query:string):Promise<Place[]>}
export interface RoutingProvider{route(from:{lat:number;lng:number},to:{lat:number;lng:number}):Promise<{minutes:number|null;source:string}>}
export interface AIPlannerProvider{generate(input:TripInput):Promise<Trip>;interpret(command:string):Promise<{action:Adjustment;day?:number}>}
export interface FileStorageProvider{upload(file:File):Promise<{id:string}>;signedURL(id:string):Promise<string>}
export const demoPlaces:PlacesProvider={async search(city,q){return getDestination(city).places.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()))}};
export const noRouting:RoutingProvider={async route(){return {minutes:null,source:'Routing jalan belum terhubung; waktu transfer adalah asumsi perencanaan.'}}};
export const noFileStorage:FileStorageProvider={async upload(){throw new Error('Penyimpanan lampiran privat belum terhubung. Gunakan catatan booking lokal.')},async signedURL(){throw new Error('Lampiran privat belum tersedia.')}};
export const rulePlanner:AIPlannerProvider={async generate(input){return generateTrip(input)},async interpret(command){const s=command.toLowerCase();let action:Adjustment;if(/santai|pelan/.test(s))action='relax';else if(/hemat|budget|biaya/.test(s))action='save';else if(/indoor|hujan|pantai/.test(s))action='indoor';else if(/kapal|laut/.test(s))action='no-sea';else if(/kuliner|makan/.test(s))action='food';else if(/transfer|dekat/.test(s))action='transfer';else if(/ulang|regenerate/.test(s))action='regenerate';else throw new Error('Gunakan perintah seperti “hari 3 lebih santai”, “hemat budget”, atau “ganti dengan indoor”. Percakapan AI bebas belum terhubung.');const day=Number(s.match(/hari\s*(\d+)/)?.[1]||0);return {action,day:day?day-1:undefined}}};
export async function runAssistant(t:Trip,command:string){const parsed=await rulePlanner.interpret(command);if(parsed.day!==undefined&&parsed.day>=t.days.length)throw new Error('Nomor hari tidak ada di perjalanan ini.');return adjustTrip(t,parsed.action,parsed.day)}
const weatherResponse=z.object({daily:z.object({time:z.array(z.string()),temperature_2m_max:z.array(z.number().nullable()),temperature_2m_min:z.array(z.number().nullable()),precipitation_probability_max:z.array(z.number().nullable())})});
export const openMeteo:WeatherProvider={async get(city,date,days){const d=getDestination(city),today=new Date().toISOString().slice(0,10),diff=Math.floor((Date.parse(date)-Date.parse(today))/86400000),provenance:Provenance={status:'Live',source:'Open-Meteo',url:'https://open-meteo.com/',updated:new Date().toISOString(),verified:true,assumptions:'Prakiraan titik area perkotaan, bukan kondisi maritim. Tidak menjamin cuaca aktivitas.'};
 if(diff<0||diff>15)return {kind:'unavailable',city,days:[],provenance:{...provenance,verified:false,status:'Estimasi'},message:'Prakiraan harian belum tersedia untuk tanggal ini. Pola musiman terverifikasi belum dihubungkan; siapkan alternatif indoor.'};
 const u=new URL('https://api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:String(d.lat),longitude:String(d.lng),daily:'temperature_2m_max,temperature_2m_min,precipitation_probability_max',timezone:d.timezone,forecast_days:'16'}).toString();const r=await fetch(u,{signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Layanan cuaca belum merespons. Rencana tetap tersimpan; coba lagi nanti.');const raw=weatherResponse.parse(await r.json()).daily;
 const list=raw.time.map((date,j)=>({date,rain:raw.precipitation_probability_max[j],min:raw.temperature_2m_min[j],max:raw.temperature_2m_max[j]})).filter(x=>x.date>=date).slice(0,days);return {kind:'forecast',city,days:list,provenance,message:list.length<days?'Sebagian tanggal berada di luar horizon prakiraan.':'Prakiraan area; dapat berubah mendekati keberangkatan.'};}};
